Set up a "Hello world" project with two apps
tchasinga/hi-back-end-rails pull request #2
Opened 2023-11-03 16:11 UTC by tchasinga

Implement a connection between a Ruby on Rails backend and the React frontend.
Understand the pros and cons of different approaches to connecting the Ruby on Rails backend with the React frontend.

2023-11-03 16:24 UTC, Davidosky007 reviewed
Hi @tchasinga 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a different frontend react app link as the link took me to someone else project, i assume this might be a mistake , kindly add the right frontend app link to your readme 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-11-03 18:41 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️ ♻️ ♻️

Hi @tchasinga,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✅ You set up Gitflow correctly 👍🏽
✅ The Linter checks passed successfully 👍🏽
✅ Add the correct links to the two repositories in the README as required 👍🏽

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly work on the seed error showing so greetings are generated and shown on the front-end app 👍🏽

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-11-03 18:41 UTC, AmaduKamara commented on db/seeds.rb
> +Greeting.create(message: "Greetings #2!")
- [ ] When I ran `rails db:seed` command to generate random greetings, I got an `UnknownAttributeError` - unknown attribute 'message' for Greeting. Kindly work on the attribute name so the seed command runs fine and random greetings are generated for the front-end app to show them as expected 👍🏽

<img width="960" alt="Screenshot 2023-11-03 at 6 22 38 PM" src="https://github.com/tchasinga/hi-back-end-react/assets/50941074/e3e5267c-08a5-485c-84e5-d728fb1b999a">

2023-11-03 21:36 UTC, frank1738 requested changes
Hi @tchasinga , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>

## Highlights

✅ The backend API endpoint is generating a random greeting

#### Keep up the good work! 😊🚀

## Required Changes ♻️
- [ ] 🌐 Just a quick heads-up! The URL you're using to fetch a random greeting in your Front End is set to the root of your backend API. To get that random greeting, you should update the URL to `http://localhost:3000/random_greeting`. Simply append `/random_greeting` to your URL, and you'll be all set .👍
- [ ] - [ ]  💡 After you've fetched the greeting and updated the state, you can directly use `greetingsCont.greeting` in your greeting component to display the random greeting. The fetched greeting is already random, so there's no need to use `Math.random()` on the data.
- [ ]  👇 Here's an example of how your component could look based on your work:

```
function Greetings() {
  const dispatch = useDispatch();
  const greetingsCont = useSelector((state) => state.greetings.greetings);

  useEffect(() => {
    dispatch(fetchGreetings());
  }, [dispatch]);

  return (
    <div>
      <h2>{greetingsCont.greeting}</h2>
    </div>
  );
}

export default Greetings;


```

- [ ]  This way, you'll simplify your code and still display the wonderful random greetings you've fetched. Keep up the good work! 😊🚀

## Optional suggestions

- [ ] 📝 Remember to write your Git commit messages in imperative tense and capitalize them. For example, `Add feature to generate random greeting endpoint` is a great way to follow this convention. 👍

- [ ] 👀 I noticed the front-end repo doesn't quite follow Git flow practice. It looks like you compared the dev branch to the main branch. Remember, with Gitflow, feature branches should be compared to the dev/development branch. Let's stick to these best practices to make our work more appealing to potential recruiters! 🌟😊

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-04 07:48 UTC, shella12 approved these changes
Hi @tchasinga, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Fixed URL ✔️ 
- Removed `Math.random` 👍 
- Implemented all requirements 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-12-22 05:59 UTC, merged